# Generated by Django 3.2 on 2021-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_foods_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='img3',
            field=models.ImageField(default='hp.jpg', upload_to='picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='img4',
            field=models.ImageField(default='gfds.jpg', upload_to='picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='img5',
            field=models.ImageField(default='pytghjfk.jpg', upload_to='picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='img6',
            field=models.ImageField(default='gtfrde.jpg', upload_to='picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='img7',
            field=models.ImageField(default='fvgk.jpg', upload_to='picture'),
            preserve_default=False,
        ),
    ]
